server:
  port: 8888

spring:
  application:
    name: music
  profiles:
    active: local
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

mybatis:
  mapper-locations: classpath:mapper/*.xml