spring:
  datasource:
    url: jdbc:mysql://175.24.147.35:3306/music?serverTimezone=Asia/Shanghai&useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: zhanglei140299@mysql.com
    driver-class-name: com.mysql.cj.jdbc.Driver